---
# This role installs, starts, and enables Pritunl and MongoDB on 
# the AWS EC2 instance created in the vpn-provision-ec2 roles

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: mongodb-org-4.0
    description: MongoDB Repository 
    file: /etc/yum.repos.d/mongodb-org-4.0
    baseurl: https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.0/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc

- name: Add multiple repositories into the same file (2/2)
  yum_repository:
    name: pritunl
    description: Pritunl Repository 
    file: /etc/yum.repos.d/pritunl
    baseurl: https://repo.pritunl.com/stable/yum/centos/7/
    gpgcheck: yes
    enabled: yes

- name: install yum-utils
  yum:
    name: yum-utils
    lock_timeout: 180
    state: latest

- name: enable ol7 developer repo
  yum_repository:
    name: ol7_developer_epel
    description: EPEL ol7 developer repo
    baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/
    gpgcheck: yes
    gpgcakey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    enabled: yes

- name: pritunl gpg keys 
  rpm_key:
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7568D9BB55FF9E5287D586017AE645C0CF8E292A
    state: present 

- name: remove iptables-services
  yum: 
    name: iptables-services
    lock_timeout: 180
    state: removed

- name: install pritunl and mongodb
  yum:
    name:
      - pritunl
      - mongodb-org
    lock_timeout: 180
    state: latest

- name: start mongodb and pritunl
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - mongod
    - pritunl 

    
