---
# This playbook performs the steps required to 
# get the Pritunl VPN default password
# Must run provision-ec2.yml and site.yml before 
# running this playbook. Then login using the 
# setup key returned in the message log in site.yml

- hosts: all
  remote_user: ec2-user
  become: yes

  tasks:

  # do this after logging in using the setup key 
  # the admin password will be in the log message
    - name: get default login
      shell: pritunl default-password
      register: login

    - debug:
        msg: "default login: {{ login.stdout_lines }}"