---
# This playbook performs the steps required to 
# deploy the single server Pritunl VPN for personal use 
# Must run provision-ec2.yml before running this playbook

# provision an aws ec2 instance 
- import_playbook: provision-ec2.yml

# configure server, load and configure software 
- hosts: pritunl
  remote_user: ec2-user
  become: yes

  roles:
     - ntp
     - vpn-install-pritunl
     - vpn-config
  