---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision an AWS EC2 instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ ec2_key_name }}"
         region: "{{ ec2_region }}"
         group: "{{ ec2_group }}"
         instance_type: "{{ ec2_instance_type }}"
         image: "{{ ec2_image }}"
         vpc_subnet_id: subnet-89fcacfe
         assign_public_ip: yes
         wait: true
         exact_count: 1
         count_tag:
            Name: basic-test
            ID: 123456-03
         instance_tags:
            Name: basic-test
            ID: 123456-03
      register: ec2

    - name: Display status of ec2 creation
      debug:
        msg: "ec2 result: {{ ec2.stdout_lines }}"

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=vpn-test
      loop: "{{ ec2.instances }}"