---
- name: Install, start, and enable pritunl and mongodb on ec2 instance just created
  hosts: vpn-test
  remote_user: ec2-user
  become: yes

  tasks:

    - name: Add multiple repositories into the same file (1/2)
      yum_repository:
        name: mongodb-org-4.0
        description: MongoDB Repository 
        file: /etc/yum.repos.d/mongodb-org-4.0
        baseurl: https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.0/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc

    - name: Add multiple repositories into the same file (2/2)
      yum_repository:
        name: pritunl
        description: Pritunl Repository 
        file: /etc/yum.repos.d/pritunl
        baseurl: https://repo.pritunl.com/stable/yum/centos/7/
        gpgcheck: yes
        enabled: yes

    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: enable ol7 developer repo
      yum_repository:
        name: ol7_developer_epel
        description: EPEL ol7 developer repo
        baseurl: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/
        gpgcheck: yes
        gpgcakey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        enabled: yes

    - name: do stuff with gpg keys
      shell: |
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp
        sudo rpm --import key.tmp
        rm -f key.tmp

    - name: remove iptables-services
      yum: 
        name: iptables-services
        state: removed

    - name: install pritunl and mongodb
      yum:
        name:
          - pritunl
          - mongodb-org
        state: latest

    - name: start mongodb and pritunl
      service:
        name: 
          - mongod
          - pritunl
        enabled: yes
        state: started

    - name: install ntp
      yum:
        name: ntp
        state: latest
    
    - name: configure ntp servers 
      blockinfile:
        path: /etc/ntp.conf
        block: |
          marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
          server time1.google.com iburst
          server time2.google.com iburst
          server time3.google.com iburst
          server time4.google.com iburst

    
