---

- name: Start VPN instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-061917f709986d213'
    region: us-west-2
  tasks:
      
    - name: Start the VPN instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        profile: becki