---
- name: Configure VPN on ec2 instance just created
  hosts: vpn-test
  remote_user: ec2-user
  become: yes

  tasks:

  - name: Increase open file limit
    blockinfile:
      path: /etc/security/limits.conf
      block: |
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        "* hard nofile 64000"
        "* soft nofile 64000"
        root hard nofile 64000
        root soft nofile 64 

  - name: get setup key
    shell: pritunl setup-key
    register: setup

  - debug:
      msg: "setup key: {{ setup.stdout_lines }} "

  - name: get default login
    shell: sudo pritunl default-password
    register: login

  - debug:
      msg: "default login: {{ login.stdout_lines }}"

